"""Add modification_entity to MouApplication and update approval process

Revision ID: 0170584dabb4
Revises: 
Create Date: 2024-06-12 10:17:02.789516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0170584dabb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DOCUMENT', 'PROJECT', 'ACTIVITIES', name='modificationentity').create(op.get_bind())
    op.add_column('mou_application', sa.Column('modification_entity', postgresql.ENUM('DOCUMENT', 'PROJECT', 'ACTIVITIES', name='modificationentity', create_type=False), nullable=True))
    op.sync_enum_values('public', 'mouapplicationstatus', ['PENDING', 'UNDER_REVIEW', 'READY_FOR_APPROVAL', 'UNDER_APPROVAL', 'APPROVED', 'REJECTED', 'REQUEST_MODIFICATION'],
                        [TableReference(table_schema='public', table_name='mou_application', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'mouapplicationstatus', ['PENDING', 'UNDER_REVIEW', 'UNDER_APPROVAL', 'APPROVED', 'REJECTED', 'REQUEST_MODIFICATION'],
                        [TableReference(table_schema='public', table_name='mou_application', column_name='status')],
                        enum_values_to_rename=[])
    op.drop_column('mou_application', 'modification_entity')
    sa.Enum('DOCUMENT', 'PROJECT', 'ACTIVITIES', name='modificationentity').drop(op.get_bind())
    # ### end Alembic commands ###
