"""Separate review and approval models

Revision ID: 01aacda08ed3
Revises: 598c5a1dd43b
Create Date: 2024-06-17 12:22:09.469868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '01aacda08ed3'
down_revision: Union[str, None] = '598c5a1dd43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'moureviewdecision', ['RECOMMEND_APPROVAL', 'REQUEST_MODIFICATION', 'REJECT', 'VERIFIED'],
                        [TableReference(table_schema='public', table_name='mou_review', column_name='decision')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'moureviewdecision', ['RECOMMEND_APPROVAL', 'REQUEST_MODIFICATION', 'REJECT'],
                        [TableReference(table_schema='public', table_name='mou_review', column_name='decision')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
