from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04ac8d513de2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='CEO'))
    # Update existing rows to set the default value
    op.execute("UPDATE party SET position = 'CEO'")
    # Remove the server_default after setting default values
    op.alter_column('party', 'position', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'position')
    # ### end Alembic commands ###
