"""changes

Revision ID: 0b7eaf0b2aa9
Revises: bdc472dbf3d0
Create Date: 2024-04-29 09:37:00.807310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0b7eaf0b2aa9'
down_revision: Union[str, None] = 'bdc472dbf3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('home_country_representative', sa.String(), nullable=True),
    sa.Column('rwanda_representative', sa.String(), nullable=True),
    sa.Column('home_country', sa.String(), nullable=True),
    sa.Column('home_country_province_state', sa.String(), nullable=True),
    sa.Column('home_country_district', sa.String(), nullable=True),
    sa.Column('home_country_avenue', sa.String(), nullable=True),
    sa.Column('home_country_po_box', sa.String(), nullable=True),
    sa.Column('rwanda_province', sa.String(), nullable=True),
    sa.Column('rwanda_district', sa.String(), nullable=True),
    sa.Column('rwanda_avenue', sa.String(), nullable=True),
    sa.Column('rwanda_po_box', sa.String(), nullable=True),
    sa.Column('organization_type_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_type_id'], ['organization_type.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_organization_created_at'), 'organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_uuid'), 'organization', ['uuid'], unique=True)
    op.create_table('document',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_type', sa.Enum('APPOINTMENT_LETTER', 'NOTIFIED_CONSTITUTION_BYLAWS', name='documenttype'), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_created_at'), 'document', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_uuid'), 'document', ['uuid'], unique=True)
    op.alter_column('user', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_document_uuid'), table_name='document')
    op.drop_index(op.f('ix_document_created_at'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_organization_uuid'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_created_at'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
