"""User model: add data manager and data reporter role

Revision ID: 17db56adc781
Revises: 
Create Date: 2024-07-17 12:35:38.243043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '17db56adc781'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'userrole', ['PARTNER', 'ADMIN', 'MOH_STAFF', 'DATA_MANAGER', 'DATA_REPORTER'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'userrole', ['PARTNER', 'ADMIN', 'MOH_STAFF'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
