"""Change modification entities to array

Revision ID: 21523610b3e2
Revises: 01aacda08ed3
Create Date: 2024-06-21 12:06:36.175267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21523610b3e2'
down_revision: Union[str, None] = '01aacda08ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add a temporary column to hold text values
    op.add_column('mou_application', sa.Column('modification_entity_tmp', sa.String(), nullable=True))

    # Step 2: Copy enum values to the temporary column
    op.execute('''
        UPDATE mou_application
        SET modification_entity_tmp = modification_entity::text
    ''')

    # Step 3: Drop the original enum column
    op.drop_column('mou_application', 'modification_entity')

    # Step 4: Add a new array column
    op.add_column('mou_application', sa.Column('modification_entity', sa.ARRAY(sa.String()), nullable=True))

    # Step 5: Copy the values from the temporary column to the new array column
    op.execute('''
        UPDATE mou_application
        SET modification_entity = ARRAY[modification_entity_tmp]
    ''')

    # Step 6: Drop the temporary column
    op.drop_column('mou_application', 'modification_entity_tmp')

    # Drop the enum type
    sa.Enum('DOCUMENT', 'PROJECT', 'ACTIVITIES', 'MOU', name='modificationentity').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the enum type
    sa.Enum('DOCUMENT', 'PROJECT', 'ACTIVITIES', 'MOU', name='modificationentity').create(op.get_bind())

    # Step 1: Add a temporary column to hold text values
    op.add_column('mou_application', sa.Column('modification_entity_tmp', sa.String(), nullable=True))

    # Step 2: Copy array values to the temporary column
    op.execute('''
        UPDATE mou_application
        SET modification_entity_tmp = modification_entity[1]
    ''')

    # Step 3: Drop the original array column
    op.drop_column('mou_application', 'modification_entity')

    # Step 4: Add a new enum column
    op.add_column('mou_application', sa.Column('modification_entity', postgresql.ENUM('DOCUMENT', 'PROJECT', 'ACTIVITIES', 'MOU', name='modificationentity'), nullable=True))

    # Step 5: Copy the values from the temporary column to the new enum column
    op.execute('''
        UPDATE mou_application
        SET modification_entity = modification_entity_tmp::modificationentity
    ''')

    # Step 6: Drop the temporary column
    op.drop_column('mou_application', 'modification_entity_tmp')
    # ### end Alembic commands ###
