"""Remove the mos level and change the approval decisions enum

Revision ID: 28b24fd28e0a
Revises: 0d89e4a7d6a5
Create Date: 2024-06-26 21:40:37.361402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '28b24fd28e0a'
down_revision: Union[str, None] = '0d89e4a7d6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'mohstafflevel', ['PARTNER_COORDINATOR', 'TECHNICAL_DEPARTMENT', 'LEGAL_ADVISOR', 'HOD', 'PS', 'MINISTER'],
                        [TableReference(table_schema='public', table_name='mou_application', column_name='next_level'), TableReference(table_schema='public', table_name='user', column_name='level')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'mouapprovaldecision', ['APPROVE', 'REQUEST_MODIFICATION', 'REJECT'],
                        [TableReference(table_schema='public', table_name='mou_approval', column_name='decision')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'mouapprovaldecision', ['APPROVE', 'REJECT'],
                        [TableReference(table_schema='public', table_name='mou_approval', column_name='decision')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'mohstafflevel', ['PARTNER_COORDINATOR', 'TECHNICAL_DEPARTMENT', 'LEGAL_ADVISOR', 'HOD', 'PS', 'MINISTER_OF_STATE', 'MINISTER'],
                        [TableReference(table_schema='public', table_name='mou_application', column_name='next_level'), TableReference(table_schema='public', table_name='user', column_name='level')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
