"""Report: fix issue with application foreign key

Revision ID: 2fffb5e2fa66
Revises: 689ff90e903e
Create Date: 2024-08-14 09:21:03.963116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fffb5e2fa66'
down_revision: Union[str, None] = '689ff90e903e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_domain_created_at', table_name='user_domain')
    op.drop_index('ix_user_domain_created_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_status', table_name='user_domain')
    op.drop_index('ix_user_domain_domain_id', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_at', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_by', table_name='user_domain')
    op.drop_index('ix_user_domain_user_id', table_name='user_domain')
    op.drop_index('ix_user_domain_uuid', table_name='user_domain')
    op.drop_table('user_domain')
    op.drop_index('ix_mou_application_report_uuid', table_name='mou_application')
    op.drop_constraint('mou_application_report_uuid_fkey', 'mou_application', type_='foreignkey')
    op.drop_column('mou_application', 'report_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_application', sa.Column('report_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('mou_application_report_uuid_fkey', 'mou_application', 'report', ['report_uuid'], ['uuid'])
    op.create_index('ix_mou_application_report_uuid', 'mou_application', ['report_uuid'], unique=False)
    op.create_table('user_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subdomain_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], name='user_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], name='user_domain_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_domain_pkey')
    )
    op.create_index('ix_user_domain_uuid', 'user_domain', ['uuid'], unique=True)
    op.create_index('ix_user_domain_user_id', 'user_domain', ['user_id'], unique=False)
    op.create_index('ix_user_domain_last_updated_by', 'user_domain', ['last_updated_by'], unique=False)
    op.create_index('ix_user_domain_last_updated_at', 'user_domain', ['last_updated_at'], unique=False)
    op.create_index('ix_user_domain_domain_id', 'user_domain', ['domain_id'], unique=False)
    op.create_index('ix_user_domain_deleted_status', 'user_domain', ['deleted_status'], unique=False)
    op.create_index('ix_user_domain_deleted_by', 'user_domain', ['deleted_by'], unique=False)
    op.create_index('ix_user_domain_created_by', 'user_domain', ['created_by'], unique=False)
    op.create_index('ix_user_domain_created_at', 'user_domain', ['created_at'], unique=False)
    # ### end Alembic commands ###
