"""Add missing values to documenttype enum

Revision ID: 32e9729936de
Revises: 6dbbed8c6fb7
Create Date: 2024-05-03 01:48:22.565531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32e9729936de'
down_revision: Union[str, None] = '6dbbed8c6fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'memo_describing_the_source_of_funds'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'memo_describing_the_long_term_objectives'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'capacity_building_transfer_plan'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'strategic_plan'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'additional_document'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
