"""Update input detail model

Revision ID: 3a4f795df854
Revises: a6f00b38978f
Create Date: 2024-05-08 22:29:22.625232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3a4f795df854'
down_revision: Union[str, None] = 'a6f00b38978f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_detail', sa.Column('district', sa.String(), nullable=True))
    op.add_column('input_detail', sa.Column('province', sa.String(), nullable=True))

    # Populate the new columns with the first element of the old array columns
    # Ensuring that this is done only where the old array columns are not empty
    op.execute('''
    UPDATE input_detail
    SET district = CASE WHEN cardinality(districts) > 0 THEN districts[1] ELSE NULL END,
        province = CASE WHEN cardinality(provinces) > 0 THEN provinces[1] ELSE NULL END
    ''')

    # Now alter columns to NOT NULL if you're sure all values are properly filled
    op.alter_column('input_detail', 'district', nullable=False)
    op.alter_column('input_detail', 'province', nullable=False)

    # Drop the old columns
    op.drop_column('input_detail', 'districts')
    op.drop_column('input_detail', 'provinces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('input_detail', sa.Column('provinces', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('input_detail', sa.Column('districts', postgresql.ARRAY(sa.String()), nullable=True))

    op.execute('''
    UPDATE input_detail
    SET districts = ARRAY[CAST(district AS VARCHAR)],
        provinces = ARRAY[CAST(province AS VARCHAR)]
    ''')

    op.drop_column('input_detail', 'province')
    op.drop_column('input_detail', 'district')
    # ### end Alembic commands ###
