"""Add duration to mou detail

Revision ID: 3f5f6b891408
Revises: 9ff86bbf7ecc
Create Date: 2024-05-13 22:55:04.319685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5f6b891408'
down_revision: Union[str, None] = '9ff86bbf7ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_detail', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mou_detail', 'duration')
    # ### end Alembic commands ###
