"""changes

Revision ID: 434469f655de
Revises: 
Create Date: 2024-05-01 22:56:33.805505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '434469f655de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('ORGANIZATION', 'MINISTRY', name='partytype'), nullable=False),
    sa.Column('responsibilities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('signatory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_created_at'), 'party', ['created_at'], unique=False)
    op.create_index(op.f('ix_party_uuid'), 'party', ['uuid'], unique=True)
    op.create_table('mou_detail',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_detail_created_at'), 'mou_detail', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_detail_uuid'), 'mou_detail', ['uuid'], unique=True)
    op.create_table('mou_application',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='mouapplicationstatus'), nullable=False),
    sa.Column('mou_detail_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['mou_detail_id'], ['mou_detail.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_application_created_at'), 'mou_application', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_application_uuid'), 'mou_application', ['uuid'], unique=True)
    op.create_table('mou_approval',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decision', sa.Enum('RECOMMEND_APPROVAL', 'RECOMMEND_REJECTION', 'REQUEST_MODIFICATION', 'APPROVE', 'REJECT', name='mouapprovaldecision'), nullable=False),
    sa.Column('approver_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mou_application_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['mou_application_id'], ['mou_application.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_approval_created_at'), 'mou_approval', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_approval_uuid'), 'mou_approval', ['uuid'], unique=True)
    op.create_table('mou_comment',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mou_application_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['mou_application_id'], ['mou_application.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_comment_created_at'), 'mou_comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_comment_uuid'), 'mou_comment', ['uuid'], unique=True)
    op.create_table('mou_review',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mou_application_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['mou_application_id'], ['mou_application.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_review_created_at'), 'mou_review', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_review_uuid'), 'mou_review', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mou_review_uuid'), table_name='mou_review')
    op.drop_index(op.f('ix_mou_review_created_at'), table_name='mou_review')
    op.drop_table('mou_review')
    op.drop_index(op.f('ix_mou_comment_uuid'), table_name='mou_comment')
    op.drop_index(op.f('ix_mou_comment_created_at'), table_name='mou_comment')
    op.drop_table('mou_comment')
    op.drop_index(op.f('ix_mou_approval_uuid'), table_name='mou_approval')
    op.drop_index(op.f('ix_mou_approval_created_at'), table_name='mou_approval')
    op.drop_table('mou_approval')
    op.drop_index(op.f('ix_mou_application_uuid'), table_name='mou_application')
    op.drop_index(op.f('ix_mou_application_created_at'), table_name='mou_application')
    op.drop_table('mou_application')
    op.drop_index(op.f('ix_mou_detail_uuid'), table_name='mou_detail')
    op.drop_index(op.f('ix_mou_detail_created_at'), table_name='mou_detail')
    op.drop_table('mou_detail')
    op.drop_index(op.f('ix_party_uuid'), table_name='party')
    op.drop_index(op.f('ix_party_created_at'), table_name='party')
    op.drop_table('party')
    # ### end Alembic commands ###
