"""Activity: add status field

Revision ID: 45128f0f84c8
Revises: 5b7bbb69fc04
Create Date: 2024-08-06 09:32:49.157242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45128f0f84c8'
down_revision: Union[str, None] = '5b7bbb69fc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('READY_FOR_REPORT', 'REPORTED', name='activitystatus').create(op.get_bind())
    op.drop_index('ix_user_domain_created_at', table_name='user_domain')
    op.drop_index('ix_user_domain_created_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_status', table_name='user_domain')
    op.drop_index('ix_user_domain_domain_id', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_at', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_by', table_name='user_domain')
    op.drop_index('ix_user_domain_user_id', table_name='user_domain')
    op.drop_index('ix_user_domain_uuid', table_name='user_domain')
    op.drop_table('user_domain')
    op.add_column('activity', sa.Column('status', postgresql.ENUM('READY_FOR_REPORT', 'REPORTED', name='activitystatus', create_type=False), nullable=True))
    op.create_index(op.f('ix_activity_end_date'), 'activity', ['end_date'], unique=False)
    op.create_index(op.f('ix_activity_fiscal_year'), 'activity', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_activity_implementer'), 'activity', ['implementer'], unique=False)
    op.create_index(op.f('ix_activity_implementer_unit'), 'activity', ['implementer_unit'], unique=False)
    op.create_index(op.f('ix_activity_start_date'), 'activity', ['start_date'], unique=False)
    op.create_index(op.f('ix_activity_status'), 'activity', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_status'), table_name='activity')
    op.drop_index(op.f('ix_activity_start_date'), table_name='activity')
    op.drop_index(op.f('ix_activity_implementer_unit'), table_name='activity')
    op.drop_index(op.f('ix_activity_implementer'), table_name='activity')
    op.drop_index(op.f('ix_activity_fiscal_year'), table_name='activity')
    op.drop_index(op.f('ix_activity_end_date'), table_name='activity')
    op.drop_column('activity', 'status')
    op.create_table('user_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subdomain_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], name='user_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], name='user_domain_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_domain_pkey')
    )
    op.create_index('ix_user_domain_uuid', 'user_domain', ['uuid'], unique=True)
    op.create_index('ix_user_domain_user_id', 'user_domain', ['user_id'], unique=False)
    op.create_index('ix_user_domain_last_updated_by', 'user_domain', ['last_updated_by'], unique=False)
    op.create_index('ix_user_domain_last_updated_at', 'user_domain', ['last_updated_at'], unique=False)
    op.create_index('ix_user_domain_domain_id', 'user_domain', ['domain_id'], unique=False)
    op.create_index('ix_user_domain_deleted_status', 'user_domain', ['deleted_status'], unique=False)
    op.create_index('ix_user_domain_deleted_by', 'user_domain', ['deleted_by'], unique=False)
    op.create_index('ix_user_domain_created_by', 'user_domain', ['created_by'], unique=False)
    op.create_index('ix_user_domain_created_at', 'user_domain', ['created_at'], unique=False)
    sa.Enum('READY_FOR_REPORT', 'REPORTED', name='activitystatus').drop(op.get_bind())
    # ### end Alembic commands ###
