"""Organization model: add rgb number

Revision ID: 4bae06203ae7
Revises: 
Create Date: 2024-07-19 22:20:19.193226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '4bae06203ae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('rgb_number', sa.String(), nullable=True))
    op.drop_constraint('user_organization_uuid_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'organization_uuid')
    op.sync_enum_values('public', 'userrole', ['PARTNER', 'ADMIN', 'MOH_STAFF'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'userrole', ['PARTNER', 'ADMIN', 'MOH_STAFF', 'DATA_MANAGER', 'DATA_REPORTER'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')],
                        enum_values_to_rename=[])
    op.add_column('user', sa.Column('organization_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_organization_uuid_fkey', 'user', 'organization', ['organization_uuid'], ['uuid'])
    op.drop_column('organization', 'rgb_number')
    # ### end Alembic commands ###
