"""Add submitted_by field to MouApplication

Revision ID: 4bfdea6c72ea
Revises: e78ffbfa1d24
Create Date: 2024-06-10 10:00:08.852493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4bfdea6c72ea'
down_revision: Union[str, None] = 'e78ffbfa1d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_application', sa.Column('submitted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('mou_application', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mou_application', 'created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('mou_application', 'submitted_by')
    # ### end Alembic commands ###
