"""Accomplishments: remove the model

Revision ID: 54e791f1928d
Revises: b3613320d997
Create Date: 2024-08-15 11:43:56.425030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54e791f1928d'
down_revision: Union[str, None] = 'b3613320d997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_activity_activity_uuid', table_name='user_activity')
    op.drop_index('ix_user_activity_created_at', table_name='user_activity')
    op.drop_index('ix_user_activity_created_by', table_name='user_activity')
    op.drop_index('ix_user_activity_deleted_by', table_name='user_activity')
    op.drop_index('ix_user_activity_deleted_status', table_name='user_activity')
    op.drop_index('ix_user_activity_last_updated_at', table_name='user_activity')
    op.drop_index('ix_user_activity_last_updated_by', table_name='user_activity')
    op.drop_index('ix_user_activity_user_uuid', table_name='user_activity')
    op.drop_index('ix_user_activity_uuid', table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index('ix_user_domain_created_at', table_name='user_domain')
    op.drop_index('ix_user_domain_created_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_status', table_name='user_domain')
    op.drop_index('ix_user_domain_domain_id', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_at', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_by', table_name='user_domain')
    op.drop_index('ix_user_domain_user_id', table_name='user_domain')
    op.drop_index('ix_user_domain_uuid', table_name='user_domain')
    op.drop_table('user_domain')
    op.drop_index('ix_accomplishment_created_at', table_name='accomplishment')
    op.drop_index('ix_accomplishment_created_by', table_name='accomplishment')
    op.drop_index('ix_accomplishment_deleted_by', table_name='accomplishment')
    op.drop_index('ix_accomplishment_deleted_status', table_name='accomplishment')
    op.drop_index('ix_accomplishment_last_updated_at', table_name='accomplishment')
    op.drop_index('ix_accomplishment_last_updated_by', table_name='accomplishment')
    op.drop_index('ix_accomplishment_report_activity_uuid', table_name='accomplishment')
    op.drop_table('accomplishment')
    op.drop_index('ix_comment_accomplishment_uuid', table_name='comment')
    op.drop_column('comment', 'accomplishment_uuid')
    op.add_column('report_activity', sa.Column('accomplishments', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_activity', 'accomplishments')
    op.add_column('comment', sa.Column('accomplishment_uuid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_accomplishment_uuid_fkey', 'comment', 'accomplishment', ['accomplishment_uuid'], ['uuid'])
    op.create_index('ix_comment_accomplishment_uuid', 'comment', ['accomplishment_uuid'], unique=False)
    op.create_table('accomplishment',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('report_activity_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('accomplishment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('accomplished_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['report_activity_uuid'], ['report_activity.uuid'], name='accomplishment_report_activity_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', name='accomplishment_pkey')
    )
    op.create_index('ix_accomplishment_uuid', 'accomplishment', ['uuid'], unique=True)
    op.create_index('ix_accomplishment_report_activity_uuid', 'accomplishment', ['report_activity_uuid'], unique=False)
    op.create_index('ix_accomplishment_last_updated_by', 'accomplishment', ['last_updated_by'], unique=False)
    op.create_index('ix_accomplishment_last_updated_at', 'accomplishment', ['last_updated_at'], unique=False)
    op.create_index('ix_accomplishment_deleted_status', 'accomplishment', ['deleted_status'], unique=False)
    op.create_index('ix_accomplishment_deleted_by', 'accomplishment', ['deleted_by'], unique=False)
    op.create_index('ix_accomplishment_created_by', 'accomplishment', ['created_by'], unique=False)
    op.create_index('ix_accomplishment_created_at', 'accomplishment', ['created_at'], unique=False)
    op.create_table('user_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subdomain_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], name='user_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], name='user_domain_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_domain_pkey')
    )
    op.create_index('ix_user_domain_uuid', 'user_domain', ['uuid'], unique=True)
    op.create_index('ix_user_domain_user_id', 'user_domain', ['user_id'], unique=False)
    op.create_index('ix_user_domain_last_updated_by', 'user_domain', ['last_updated_by'], unique=False)
    op.create_index('ix_user_domain_last_updated_at', 'user_domain', ['last_updated_at'], unique=False)
    op.create_index('ix_user_domain_domain_id', 'user_domain', ['domain_id'], unique=False)
    op.create_index('ix_user_domain_deleted_status', 'user_domain', ['deleted_status'], unique=False)
    op.create_index('ix_user_domain_deleted_by', 'user_domain', ['deleted_by'], unique=False)
    op.create_index('ix_user_domain_created_by', 'user_domain', ['created_by'], unique=False)
    op.create_index('ix_user_domain_created_at', 'user_domain', ['created_at'], unique=False)
    op.create_table('user_activity',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_uuid'], ['activity.uuid'], name='user_activity_activity_uuid_fkey'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name='user_activity_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_activity_pkey')
    )
    op.create_index('ix_user_activity_uuid', 'user_activity', ['uuid'], unique=True)
    op.create_index('ix_user_activity_user_uuid', 'user_activity', ['user_uuid'], unique=False)
    op.create_index('ix_user_activity_last_updated_by', 'user_activity', ['last_updated_by'], unique=False)
    op.create_index('ix_user_activity_last_updated_at', 'user_activity', ['last_updated_at'], unique=False)
    op.create_index('ix_user_activity_deleted_status', 'user_activity', ['deleted_status'], unique=False)
    op.create_index('ix_user_activity_deleted_by', 'user_activity', ['deleted_by'], unique=False)
    op.create_index('ix_user_activity_created_by', 'user_activity', ['created_by'], unique=False)
    op.create_index('ix_user_activity_created_at', 'user_activity', ['created_at'], unique=False)
    op.create_index('ix_user_activity_activity_uuid', 'user_activity', ['activity_uuid'], unique=False)
    # ### end Alembic commands ###
