"""Separate review and approval models

Revision ID: 598c5a1dd43b
Revises: 7ef2ae0e630c
Create Date: 2024-06-17 10:44:05.747790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '598c5a1dd43b'
down_revision: Union[str, None] = '7ef2ae0e630c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_approval', sa.Column('current_approver_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('mou_approval_approver_id_fkey', 'mou_approval', type_='foreignkey')
    op.create_foreign_key(None, 'mou_approval', 'user', ['current_approver_id'], ['uuid'])
    op.drop_column('mou_approval', 'approver_id')
    op.add_column('mou_review', sa.Column('current_review_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.drop_constraint('mou_review_user_id_fkey', 'mou_review', type_='foreignkey')
    op.create_foreign_key(None, 'mou_review', 'user', ['current_review_id'], ['uuid'])
    op.drop_column('mou_review', 'user_id')
    op.sync_enum_values('public', 'mouapprovaldecision', ['APPROVE', 'REJECT'],
                        [TableReference(table_schema='public', table_name='mou_approval', column_name='decision')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'moureviewdecision', ['RECOMMEND_APPROVAL', 'REQUEST_MODIFICATION', 'REJECT'],
                        [TableReference(table_schema='public', table_name='mou_review', column_name='decision')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'moureviewdecision', ['VERIFIED', 'NOT_YET_VERIFIED'],
                        [TableReference(table_schema='public', table_name='mou_review', column_name='decision')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'mouapprovaldecision', ['RECOMMEND_APPROVAL', 'RECOMMEND_REJECTION', 'REQUEST_MODIFICATION', 'APPROVE', 'REJECT'],
                        [TableReference(table_schema='public', table_name='mou_approval', column_name='decision')],
                        enum_values_to_rename=[])
    op.add_column('mou_review', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mou_review', type_='foreignkey')
    op.create_foreign_key('mou_review_user_id_fkey', 'mou_review', 'user', ['user_id'], ['uuid'])
    op.drop_column('mou_review', 'current_review_id')
    op.add_column('mou_approval', sa.Column('approver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mou_approval', type_='foreignkey')
    op.create_foreign_key('mou_approval_approver_id_fkey', 'mou_approval', 'user', ['approver_id'], ['uuid'])
    op.drop_column('mou_approval', 'current_approver_id')
    # ### end Alembic commands ###
