"""User: domains and partner organization name

Revision ID: 5a023283bfeb
Revises: 
Create Date: 2024-08-05 10:23:22.625679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5a023283bfeb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_domain_created_at', table_name='user_domain')
    op.drop_index('ix_user_domain_created_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_status', table_name='user_domain')
    op.drop_index('ix_user_domain_domain_id', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_at', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_by', table_name='user_domain')
    op.drop_index('ix_user_domain_user_id', table_name='user_domain')
    op.drop_index('ix_user_domain_uuid', table_name='user_domain')
    op.drop_table('user_domain')
    op.add_column('user', sa.Column('organization_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.add_column('user', sa.Column('partner_organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization', ['organization_uuid'], ['uuid'])
    op.sync_enum_values('public', 'userrole', ['PARTNER', 'ADMIN', 'MOH_STAFF', 'DATA_MANAGER', 'DATA_REPORTER'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'userrole', ['PARTNER', 'ADMIN', 'MOH_STAFF'],
                        [TableReference(table_schema='public', table_name='user', column_name='role')],
                        enum_values_to_rename=[])
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'partner_organization_name')
    op.drop_column('user', 'organization_uuid')
    op.create_table('user_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subdomain_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], name='user_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], name='user_domain_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_domain_pkey')
    )
    op.create_index('ix_user_domain_uuid', 'user_domain', ['uuid'], unique=True)
    op.create_index('ix_user_domain_user_id', 'user_domain', ['user_id'], unique=False)
    op.create_index('ix_user_domain_last_updated_by', 'user_domain', ['last_updated_by'], unique=False)
    op.create_index('ix_user_domain_last_updated_at', 'user_domain', ['last_updated_at'], unique=False)
    op.create_index('ix_user_domain_domain_id', 'user_domain', ['domain_id'], unique=False)
    op.create_index('ix_user_domain_deleted_status', 'user_domain', ['deleted_status'], unique=False)
    op.create_index('ix_user_domain_deleted_by', 'user_domain', ['deleted_by'], unique=False)
    op.create_index('ix_user_domain_created_by', 'user_domain', ['created_by'], unique=False)
    op.create_index('ix_user_domain_created_at', 'user_domain', ['created_at'], unique=False)
    # ### end Alembic commands ###
