"""application reviewer

Revision ID: 603dc6f80a4c
Revises: e717f2d09291
Create Date: 2024-05-21 22:36:49.346598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '603dc6f80a4c'
down_revision: Union[str, None] = 'e717f2d09291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_application', sa.Column('current_reviewer_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'mou_application', 'user', ['current_reviewer_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mou_application', type_='foreignkey')
    op.drop_column('mou_application', 'current_reviewer_id')
    # ### end Alembic commands ###
