"""Project: other funding source

Revision ID: 621df8d701b9
Revises: e3c5a2ce30f8
Create Date: 2024-07-24 11:33:26.310519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '621df8d701b9'
down_revision: Union[str, None] = 'e3c5a2ce30f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('other_funding_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('project', 'funding_source_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'funding_source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('project', 'other_funding_source')
    # ### end Alembic commands ###
