"""Add models for report and report activities

Revision ID: 689ff90e903e
Revises: 303eb8626bb1
Create Date: 2024-08-13 22:42:40.511034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '689ff90e903e'
down_revision: Union[str, None] = '303eb8626bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'APPROVED', 'NEEDS_CHANGE', name='reportactivitystatus').create(op.get_bind())
    sa.Enum('PENDING', 'REPORTED', 'APPROVED', name='reportstatus').create(op.get_bind())
    op.create_table('report',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mou_application_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('reported_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('organization_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('project_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'REPORTED', 'APPROVED', name='reportstatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['mou_application_uuid'], ['mou_application.uuid'], ),
    sa.ForeignKeyConstraint(['organization_uuid'], ['organization.uuid'], ),
    sa.ForeignKeyConstraint(['project_uuid'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_created_at'), 'report', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_created_by'), 'report', ['created_by'], unique=False)
    op.create_index(op.f('ix_report_deleted_by'), 'report', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_report_deleted_status'), 'report', ['deleted_status'], unique=False)
    op.create_index(op.f('ix_report_last_updated_at'), 'report', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_report_last_updated_by'), 'report', ['last_updated_by'], unique=False)
    op.create_index(op.f('ix_report_mou_application_uuid'), 'report', ['mou_application_uuid'], unique=False)
    op.create_index(op.f('ix_report_organization_uuid'), 'report', ['organization_uuid'], unique=False)
    op.create_index(op.f('ix_report_project_uuid'), 'report', ['project_uuid'], unique=False)
    op.create_index(op.f('ix_report_uuid'), 'report', ['uuid'], unique=True)
    op.create_table('report_activity',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('reported_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executed_budget', sa.Float(), nullable=False),
    sa.Column('actual_start_date', sa.DateTime(), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'NEEDS_CHANGE', name='reportactivitystatus', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['report_uuid'], ['report.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_activity_created_at'), 'report_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_activity_created_by'), 'report_activity', ['created_by'], unique=False)
    op.create_index(op.f('ix_report_activity_deleted_by'), 'report_activity', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_report_activity_deleted_status'), 'report_activity', ['deleted_status'], unique=False)
    op.create_index(op.f('ix_report_activity_last_updated_at'), 'report_activity', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_report_activity_last_updated_by'), 'report_activity', ['last_updated_by'], unique=False)
    op.create_index(op.f('ix_report_activity_report_uuid'), 'report_activity', ['report_uuid'], unique=False)
    op.create_index(op.f('ix_report_activity_status'), 'report_activity', ['status'], unique=False)
    op.create_index(op.f('ix_report_activity_uuid'), 'report_activity', ['uuid'], unique=True)
    op.create_table('accomplishment',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_activity_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('accomplishment_date', sa.DateTime(), nullable=True),
    sa.Column('accomplished_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['report_activity_uuid'], ['report_activity.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accomplishment_created_at'), 'accomplishment', ['created_at'], unique=False)
    op.create_index(op.f('ix_accomplishment_created_by'), 'accomplishment', ['created_by'], unique=False)
    op.create_index(op.f('ix_accomplishment_deleted_by'), 'accomplishment', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_accomplishment_deleted_status'), 'accomplishment', ['deleted_status'], unique=False)
    op.create_index(op.f('ix_accomplishment_last_updated_at'), 'accomplishment', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_accomplishment_last_updated_by'), 'accomplishment', ['last_updated_by'], unique=False)
    op.create_index(op.f('ix_accomplishment_report_activity_uuid'), 'accomplishment', ['report_activity_uuid'], unique=False)
    op.create_index(op.f('ix_accomplishment_uuid'), 'accomplishment', ['uuid'], unique=True)
    op.create_table('comment',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('report_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('report_activity_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('accomplishment_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['accomplishment_uuid'], ['accomplishment.uuid'], ),
    sa.ForeignKeyConstraint(['report_activity_uuid'], ['report_activity.uuid'], ),
    sa.ForeignKeyConstraint(['report_uuid'], ['report.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_accomplishment_uuid'), 'comment', ['accomplishment_uuid'], unique=False)
    op.create_index(op.f('ix_comment_created_at'), 'comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_comment_created_by'), 'comment', ['created_by'], unique=False)
    op.create_index(op.f('ix_comment_deleted_by'), 'comment', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_comment_deleted_status'), 'comment', ['deleted_status'], unique=False)
    op.create_index(op.f('ix_comment_last_updated_at'), 'comment', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_comment_last_updated_by'), 'comment', ['last_updated_by'], unique=False)
    op.create_index(op.f('ix_comment_report_activity_uuid'), 'comment', ['report_activity_uuid'], unique=False)
    op.create_index(op.f('ix_comment_report_uuid'), 'comment', ['report_uuid'], unique=False)
    op.create_index(op.f('ix_comment_user_uuid'), 'comment', ['user_uuid'], unique=False)
    op.create_index(op.f('ix_comment_uuid'), 'comment', ['uuid'], unique=True)
    op.drop_index('ix_user_domain_created_at', table_name='user_domain')
    op.drop_index('ix_user_domain_created_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_status', table_name='user_domain')
    op.drop_index('ix_user_domain_domain_id', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_at', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_by', table_name='user_domain')
    op.drop_index('ix_user_domain_user_id', table_name='user_domain')
    op.drop_index('ix_user_domain_uuid', table_name='user_domain')
    op.drop_table('user_domain')
    op.add_column('activity', sa.Column('report_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_activity_report_uuid'), 'activity', ['report_uuid'], unique=False)
    op.create_foreign_key(None, 'activity', 'report', ['report_uuid'], ['uuid'])
    op.add_column('mou_application', sa.Column('report_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_mou_application_report_uuid'), 'mou_application', ['report_uuid'], unique=False)
    op.create_foreign_key(None, 'mou_application', 'report', ['report_uuid'], ['uuid'])
    op.add_column('project', sa.Column('report_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_project_report_uuid'), 'project', ['report_uuid'], unique=False)
    op.create_foreign_key(None, 'project', 'report', ['report_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_index(op.f('ix_project_report_uuid'), table_name='project')
    op.drop_column('project', 'report_uuid')
    op.drop_constraint(None, 'mou_application', type_='foreignkey')
    op.drop_index(op.f('ix_mou_application_report_uuid'), table_name='mou_application')
    op.drop_column('mou_application', 'report_uuid')
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_index(op.f('ix_activity_report_uuid'), table_name='activity')
    op.drop_column('activity', 'report_uuid')
    op.create_table('user_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subdomain_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], name='user_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], name='user_domain_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_domain_pkey')
    )
    op.create_index('ix_user_domain_uuid', 'user_domain', ['uuid'], unique=True)
    op.create_index('ix_user_domain_user_id', 'user_domain', ['user_id'], unique=False)
    op.create_index('ix_user_domain_last_updated_by', 'user_domain', ['last_updated_by'], unique=False)
    op.create_index('ix_user_domain_last_updated_at', 'user_domain', ['last_updated_at'], unique=False)
    op.create_index('ix_user_domain_domain_id', 'user_domain', ['domain_id'], unique=False)
    op.create_index('ix_user_domain_deleted_status', 'user_domain', ['deleted_status'], unique=False)
    op.create_index('ix_user_domain_deleted_by', 'user_domain', ['deleted_by'], unique=False)
    op.create_index('ix_user_domain_created_by', 'user_domain', ['created_by'], unique=False)
    op.create_index('ix_user_domain_created_at', 'user_domain', ['created_at'], unique=False)
    op.drop_index(op.f('ix_comment_uuid'), table_name='comment')
    op.drop_index(op.f('ix_comment_user_uuid'), table_name='comment')
    op.drop_index(op.f('ix_comment_report_uuid'), table_name='comment')
    op.drop_index(op.f('ix_comment_report_activity_uuid'), table_name='comment')
    op.drop_index(op.f('ix_comment_last_updated_by'), table_name='comment')
    op.drop_index(op.f('ix_comment_last_updated_at'), table_name='comment')
    op.drop_index(op.f('ix_comment_deleted_status'), table_name='comment')
    op.drop_index(op.f('ix_comment_deleted_by'), table_name='comment')
    op.drop_index(op.f('ix_comment_created_by'), table_name='comment')
    op.drop_index(op.f('ix_comment_created_at'), table_name='comment')
    op.drop_index(op.f('ix_comment_accomplishment_uuid'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_accomplishment_uuid'), table_name='accomplishment')
    op.drop_index(op.f('ix_accomplishment_report_activity_uuid'), table_name='accomplishment')
    op.drop_index(op.f('ix_accomplishment_last_updated_by'), table_name='accomplishment')
    op.drop_index(op.f('ix_accomplishment_last_updated_at'), table_name='accomplishment')
    op.drop_index(op.f('ix_accomplishment_deleted_status'), table_name='accomplishment')
    op.drop_index(op.f('ix_accomplishment_deleted_by'), table_name='accomplishment')
    op.drop_index(op.f('ix_accomplishment_created_by'), table_name='accomplishment')
    op.drop_index(op.f('ix_accomplishment_created_at'), table_name='accomplishment')
    op.drop_table('accomplishment')
    op.drop_index(op.f('ix_report_activity_uuid'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_status'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_report_uuid'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_last_updated_by'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_last_updated_at'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_deleted_status'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_deleted_by'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_created_by'), table_name='report_activity')
    op.drop_index(op.f('ix_report_activity_created_at'), table_name='report_activity')
    op.drop_table('report_activity')
    op.drop_index(op.f('ix_report_uuid'), table_name='report')
    op.drop_index(op.f('ix_report_project_uuid'), table_name='report')
    op.drop_index(op.f('ix_report_organization_uuid'), table_name='report')
    op.drop_index(op.f('ix_report_mou_application_uuid'), table_name='report')
    op.drop_index(op.f('ix_report_last_updated_by'), table_name='report')
    op.drop_index(op.f('ix_report_last_updated_at'), table_name='report')
    op.drop_index(op.f('ix_report_deleted_status'), table_name='report')
    op.drop_index(op.f('ix_report_deleted_by'), table_name='report')
    op.drop_index(op.f('ix_report_created_by'), table_name='report')
    op.drop_index(op.f('ix_report_created_at'), table_name='report')
    op.drop_table('report')
    sa.Enum('PENDING', 'REPORTED', 'APPROVED', name='reportstatus').drop(op.get_bind())
    sa.Enum('PENDING', 'APPROVED', 'NEEDS_CHANGE', name='reportactivitystatus').drop(op.get_bind())
    # ### end Alembic commands ###
