"""changes project

Revision ID: 6dbbed8c6fb7
Revises: c6fd67e9ef06
Create Date: 2024-05-03 01:45:31.351125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbbed8c6fb7'
down_revision: Union[str, None] = 'c6fd67e9ef06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
