"""Activity: change the status

Revision ID: 7548ed238c10
Revises: 54e791f1928d
Create Date: 2024-08-15 17:52:40.947305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7548ed238c10'
down_revision: Union[str, None] = '54e791f1928d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_activity_activity_uuid', table_name='user_activity')
    op.drop_index('ix_user_activity_created_at', table_name='user_activity')
    op.drop_index('ix_user_activity_created_by', table_name='user_activity')
    op.drop_index('ix_user_activity_deleted_by', table_name='user_activity')
    op.drop_index('ix_user_activity_deleted_status', table_name='user_activity')
    op.drop_index('ix_user_activity_last_updated_at', table_name='user_activity')
    op.drop_index('ix_user_activity_last_updated_by', table_name='user_activity')
    op.drop_index('ix_user_activity_user_uuid', table_name='user_activity')
    op.drop_index('ix_user_activity_uuid', table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index('ix_user_domain_created_at', table_name='user_domain')
    op.drop_index('ix_user_domain_created_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_by', table_name='user_domain')
    op.drop_index('ix_user_domain_deleted_status', table_name='user_domain')
    op.drop_index('ix_user_domain_domain_id', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_at', table_name='user_domain')
    op.drop_index('ix_user_domain_last_updated_by', table_name='user_domain')
    op.drop_index('ix_user_domain_user_id', table_name='user_domain')
    op.drop_index('ix_user_domain_uuid', table_name='user_domain')
    op.drop_table('user_domain')
    op.add_column('activity', sa.Column('report_status', postgresql.ENUM('READY_FOR_REPORT', 'REPORTED', name='activityreportingstatus', create_type=False), nullable=True))
    op.create_index(op.f('ix_activity_report_status'), 'activity', ['report_status'], unique=False)
    op.sync_enum_values('public', 'activitystatus', ['NOT_STARTED', 'ON_GOING', 'COMPLETED'],
                        [TableReference(table_schema='public', table_name='activity', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'activitystatus', ['READY_FOR_REPORT', 'REPORTED'],
                        [TableReference(table_schema='public', table_name='activity', column_name='status')],
                        enum_values_to_rename=[])
    op.drop_index(op.f('ix_activity_report_status'), table_name='activity')
    op.drop_column('activity', 'report_status')
    op.create_table('user_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subdomain_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], name='user_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], name='user_domain_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_domain_pkey')
    )
    op.create_index('ix_user_domain_uuid', 'user_domain', ['uuid'], unique=True)
    op.create_index('ix_user_domain_user_id', 'user_domain', ['user_id'], unique=False)
    op.create_index('ix_user_domain_last_updated_by', 'user_domain', ['last_updated_by'], unique=False)
    op.create_index('ix_user_domain_last_updated_at', 'user_domain', ['last_updated_at'], unique=False)
    op.create_index('ix_user_domain_domain_id', 'user_domain', ['domain_id'], unique=False)
    op.create_index('ix_user_domain_deleted_status', 'user_domain', ['deleted_status'], unique=False)
    op.create_index('ix_user_domain_deleted_by', 'user_domain', ['deleted_by'], unique=False)
    op.create_index('ix_user_domain_created_by', 'user_domain', ['created_by'], unique=False)
    op.create_index('ix_user_domain_created_at', 'user_domain', ['created_at'], unique=False)
    op.create_table('user_activity',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_uuid'], ['activity.uuid'], name='user_activity_activity_uuid_fkey'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name='user_activity_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_activity_pkey')
    )
    op.create_index('ix_user_activity_uuid', 'user_activity', ['uuid'], unique=True)
    op.create_index('ix_user_activity_user_uuid', 'user_activity', ['user_uuid'], unique=False)
    op.create_index('ix_user_activity_last_updated_by', 'user_activity', ['last_updated_by'], unique=False)
    op.create_index('ix_user_activity_last_updated_at', 'user_activity', ['last_updated_at'], unique=False)
    op.create_index('ix_user_activity_deleted_status', 'user_activity', ['deleted_status'], unique=False)
    op.create_index('ix_user_activity_deleted_by', 'user_activity', ['deleted_by'], unique=False)
    op.create_index('ix_user_activity_created_by', 'user_activity', ['created_by'], unique=False)
    op.create_index('ix_user_activity_created_at', 'user_activity', ['created_at'], unique=False)
    op.create_index('ix_user_activity_activity_uuid', 'user_activity', ['activity_uuid'], unique=False)
    # ### end Alembic commands ###
