"""Party: add reason for extended duration

Revision ID: 7b526340724d
Revises: 5c4e71a73c52
Create Date: 2024-07-26 01:09:46.427976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7b526340724d'
down_revision: Union[str, None] = '5c4e71a73c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('reason_for_extended_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('project', 'fiscal_year_budgets',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'fiscal_year_budgets',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('party', 'reason_for_extended_duration')
    # ### end Alembic commands ###
