"""Add verified status to mou approval or review

Revision ID: 7ef2ae0e630c
Revises: 0170584dabb4
Create Date: 2024-06-12 15:15:04.039134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '7ef2ae0e630c'
down_revision: Union[str, None] = '0170584dabb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'mouapprovalorreviewdecision', ['RECOMMEND_APPROVAL', 'RECOMMEND_REJECTION', 'REQUEST_MODIFICATION', 'APPROVE', 'REJECT', 'VERIFIED'],
                        [TableReference(table_schema='public', table_name='mou_approval_or_review', column_name='decision')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'mouapprovalorreviewdecision', ['RECOMMEND_APPROVAL', 'RECOMMEND_REJECTION', 'REQUEST_MODIFICATION', 'APPROVE', 'REJECT'],
                        [TableReference(table_schema='public', table_name='mou_approval_or_review', column_name='decision')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
