"""update approval mou

Revision ID: 8723ce9562ec
Revises: 59e60052c68d
Create Date: 2024-05-21 20:39:10.957584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8723ce9562ec'
down_revision: Union[str, None] = '59e60052c68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_approval_or_review', sa.Column('current_reviewer_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('mou_approval_or_review_approver_or_reviewer_id_fkey', 'mou_approval_or_review', type_='foreignkey')
    op.create_foreign_key(None, 'mou_approval_or_review', 'user', ['current_reviewer_id'], ['uuid'])
    op.drop_column('mou_approval_or_review', 'approver_or_reviewer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_approval_or_review', sa.Column('approver_or_reviewer_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mou_approval_or_review', type_='foreignkey')
    op.create_foreign_key('mou_approval_or_review_approver_or_reviewer_id_fkey', 'mou_approval_or_review', 'user', ['approver_or_reviewer_id'], ['uuid'])
    op.drop_column('mou_approval_or_review', 'current_reviewer_id')
    # ### end Alembic commands ###
