"""made a lot of changes

Revision ID: 8edff809f40e
Revises: 
Create Date: 2024-05-07 01:04:35.590511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8edff809f40e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_type',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_type_created_at'), 'budget_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_budget_type_uuid'), 'budget_type', ['uuid'], unique=True)
    op.create_table('domain_intervention',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_intervention_created_at'), 'domain_intervention', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_intervention_uuid'), 'domain_intervention', ['uuid'], unique=True)
    op.create_table('funding_source',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_source_created_at'), 'funding_source', ['created_at'], unique=False)
    op.create_index(op.f('ix_funding_source_uuid'), 'funding_source', ['uuid'], unique=True)
    op.create_table('funding_unit',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_unit_created_at'), 'funding_unit', ['created_at'], unique=False)
    op.create_index(op.f('ix_funding_unit_uuid'), 'funding_unit', ['uuid'], unique=True)
    op.create_table('input_category',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_category_created_at'), 'input_category', ['created_at'], unique=False)
    op.create_index(op.f('ix_input_category_uuid'), 'input_category', ['uuid'], unique=True)
    op.create_table('organization_type',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_type_created_at'), 'organization_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_type_uuid'), 'organization_type', ['uuid'], unique=True)
    op.create_table('user',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('PARTNER', 'ADMIN', 'SWAPTEAM_MEMBER', name='userrole'), nullable=False),
    sa.Column('level', sa.Enum('PARTNER_COORDINATOR', 'TECHNICAL_DEPARTMENT', 'LEGAL_ADVISOR', 'HOD', 'PS', 'MINISTER_OF_STATE', 'MINISTER', name='swapteamlevel'), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('input',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['input_category.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_created_at'), 'input', ['created_at'], unique=False)
    op.create_index(op.f('ix_input_uuid'), 'input', ['uuid'], unique=True)
    op.create_table('organization',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('home_country_representative', sa.String(), nullable=True),
    sa.Column('rwanda_representative', sa.String(), nullable=True),
    sa.Column('home_country', sa.String(), nullable=True),
    sa.Column('home_country_province_state', sa.String(), nullable=True),
    sa.Column('home_country_district', sa.String(), nullable=True),
    sa.Column('home_country_avenue', sa.String(), nullable=True),
    sa.Column('home_country_po_box', sa.String(), nullable=True),
    sa.Column('rwanda_province', sa.String(), nullable=True),
    sa.Column('rwanda_district', sa.String(), nullable=True),
    sa.Column('rwanda_avenue', sa.String(), nullable=True),
    sa.Column('rwanda_po_box', sa.String(), nullable=True),
    sa.Column('organization_type_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_type_id'], ['organization_type.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_organization_created_at'), 'organization', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_index(op.f('ix_organization_uuid'), 'organization', ['uuid'], unique=True)
    op.create_table('sub_domain',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_domain_created_at'), 'sub_domain', ['created_at'], unique=False)
    op.create_index(op.f('ix_sub_domain_uuid'), 'sub_domain', ['uuid'], unique=True)
    op.create_table('project',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain_intervention_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('budget_type_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('funding_unit_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('funding_source_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['budget_type_id'], ['budget_type.uuid'], ),
    sa.ForeignKeyConstraint(['domain_intervention_id'], ['domain_intervention.uuid'], ),
    sa.ForeignKeyConstraint(['funding_source_id'], ['funding_source.uuid'], ),
    sa.ForeignKeyConstraint(['funding_unit_id'], ['funding_unit.uuid'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_created_at'), 'project', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_uuid'), 'project', ['uuid'], unique=True)
    op.create_table('activity',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('implementer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('implementer_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_domain_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.uuid'], ),
    sa.ForeignKeyConstraint(['sub_domain_id'], ['sub_domain.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_created_at'), 'activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_uuid'), 'activity', ['uuid'], unique=True)
    op.create_table('goal',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_created_at'), 'goal', ['created_at'], unique=False)
    op.create_index(op.f('ix_goal_uuid'), 'goal', ['uuid'], unique=True)
    op.create_table('mou_detail',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_detail_created_at'), 'mou_detail', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_detail_uuid'), 'mou_detail', ['uuid'], unique=True)
    op.create_table('operational_zone',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('districts', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_zone_created_at'), 'operational_zone', ['created_at'], unique=False)
    op.create_index(op.f('ix_operational_zone_uuid'), 'operational_zone', ['uuid'], unique=True)
    op.create_table('input_detail',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('input_category_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('input_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('districts', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('provinces', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.uuid'], ),
    sa.ForeignKeyConstraint(['input_category_id'], ['input_category.uuid'], ),
    sa.ForeignKeyConstraint(['input_id'], ['input.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_input_detail_created_at'), 'input_detail', ['created_at'], unique=False)
    op.create_index(op.f('ix_input_detail_uuid'), 'input_detail', ['uuid'], unique=True)
    op.create_table('mou_application',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='mouapplicationstatus'), nullable=False),
    sa.Column('mou_detail_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['mou_detail_id'], ['mou_detail.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_application_created_at'), 'mou_application', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_application_uuid'), 'mou_application', ['uuid'], unique=True)
    op.create_table('party',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('ORGANIZATION', 'MINISTRY', name='partytype'), nullable=False),
    sa.Column('responsibilities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('signatory', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mou_detail_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['mou_detail_id'], ['mou_detail.uuid'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_created_at'), 'party', ['created_at'], unique=False)
    op.create_index(op.f('ix_party_uuid'), 'party', ['uuid'], unique=True)
    op.create_table('document',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_type', sa.Enum('APPOINTMENT_LETTER', 'NOTIFIED_CONSTITUTION_BYLAWS', 'CAPACITY_BUILDING_TRANSFER_PLAN', 'MEMO_DESCRIBING_THE_SOURCE_OF_FUNDS', 'MEMO_DESCRIBING_THE_LONG_TERM_OBJECTIVES', 'STRATEGIC_PLAN', 'ADDITIONAL_DOCUMENT', name='documenttype'), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('mou_detail_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('mou_application_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['mou_application_id'], ['mou_application.uuid'], ),
    sa.ForeignKeyConstraint(['mou_detail_id'], ['mou_detail.uuid'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_created_at'), 'document', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_uuid'), 'document', ['uuid'], unique=True)
    op.create_table('mou_approval',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('decision', sa.Enum('RECOMMEND_APPROVAL', 'RECOMMEND_REJECTION', 'REQUEST_MODIFICATION', 'APPROVE', 'REJECT', name='mouapprovaldecision'), nullable=False),
    sa.Column('approver_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mou_application_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['mou_application_id'], ['mou_application.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_approval_created_at'), 'mou_approval', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_approval_uuid'), 'mou_approval', ['uuid'], unique=True)
    op.create_table('mou_review',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mou_application_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['mou_application_id'], ['mou_application.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_review_created_at'), 'mou_review', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_review_uuid'), 'mou_review', ['uuid'], unique=True)
    op.create_table('mou_comment',
    sa.Column('uuid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted_status', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mou_application_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('mou_approval_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('mou_review_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['mou_application_id'], ['mou_application.uuid'], ),
    sa.ForeignKeyConstraint(['mou_approval_id'], ['mou_approval.uuid'], ),
    sa.ForeignKeyConstraint(['mou_review_id'], ['mou_review.uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mou_comment_created_at'), 'mou_comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_mou_comment_uuid'), 'mou_comment', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mou_comment_uuid'), table_name='mou_comment')
    op.drop_index(op.f('ix_mou_comment_created_at'), table_name='mou_comment')
    op.drop_table('mou_comment')
    op.drop_index(op.f('ix_mou_review_uuid'), table_name='mou_review')
    op.drop_index(op.f('ix_mou_review_created_at'), table_name='mou_review')
    op.drop_table('mou_review')
    op.drop_index(op.f('ix_mou_approval_uuid'), table_name='mou_approval')
    op.drop_index(op.f('ix_mou_approval_created_at'), table_name='mou_approval')
    op.drop_table('mou_approval')
    op.drop_index(op.f('ix_document_uuid'), table_name='document')
    op.drop_index(op.f('ix_document_created_at'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_party_uuid'), table_name='party')
    op.drop_index(op.f('ix_party_created_at'), table_name='party')
    op.drop_table('party')
    op.drop_index(op.f('ix_mou_application_uuid'), table_name='mou_application')
    op.drop_index(op.f('ix_mou_application_created_at'), table_name='mou_application')
    op.drop_table('mou_application')
    op.drop_index(op.f('ix_input_detail_uuid'), table_name='input_detail')
    op.drop_index(op.f('ix_input_detail_created_at'), table_name='input_detail')
    op.drop_table('input_detail')
    op.drop_index(op.f('ix_operational_zone_uuid'), table_name='operational_zone')
    op.drop_index(op.f('ix_operational_zone_created_at'), table_name='operational_zone')
    op.drop_table('operational_zone')
    op.drop_index(op.f('ix_mou_detail_uuid'), table_name='mou_detail')
    op.drop_index(op.f('ix_mou_detail_created_at'), table_name='mou_detail')
    op.drop_table('mou_detail')
    op.drop_index(op.f('ix_goal_uuid'), table_name='goal')
    op.drop_index(op.f('ix_goal_created_at'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_activity_uuid'), table_name='activity')
    op.drop_index(op.f('ix_activity_created_at'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_project_uuid'), table_name='project')
    op.drop_index(op.f('ix_project_created_at'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_sub_domain_uuid'), table_name='sub_domain')
    op.drop_index(op.f('ix_sub_domain_created_at'), table_name='sub_domain')
    op.drop_table('sub_domain')
    op.drop_index(op.f('ix_organization_uuid'), table_name='organization')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_created_at'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_input_uuid'), table_name='input')
    op.drop_index(op.f('ix_input_created_at'), table_name='input')
    op.drop_table('input')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_organization_type_uuid'), table_name='organization_type')
    op.drop_index(op.f('ix_organization_type_created_at'), table_name='organization_type')
    op.drop_table('organization_type')
    op.drop_index(op.f('ix_input_category_uuid'), table_name='input_category')
    op.drop_index(op.f('ix_input_category_created_at'), table_name='input_category')
    op.drop_table('input_category')
    op.drop_index(op.f('ix_funding_unit_uuid'), table_name='funding_unit')
    op.drop_index(op.f('ix_funding_unit_created_at'), table_name='funding_unit')
    op.drop_table('funding_unit')
    op.drop_index(op.f('ix_funding_source_uuid'), table_name='funding_source')
    op.drop_index(op.f('ix_funding_source_created_at'), table_name='funding_source')
    op.drop_table('funding_source')
    op.drop_index(op.f('ix_domain_intervention_uuid'), table_name='domain_intervention')
    op.drop_index(op.f('ix_domain_intervention_created_at'), table_name='domain_intervention')
    op.drop_table('domain_intervention')
    op.drop_index(op.f('ix_budget_type_uuid'), table_name='budget_type')
    op.drop_index(op.f('ix_budget_type_created_at'), table_name='budget_type')
    op.drop_table('budget_type')
    # ### end Alembic commands ###
