"""changes

Revision ID: 931d5a2d8712
Revises: 985f4e37b466
Create Date: 2024-11-19 22:50:37.828294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "931d5a2d8712"
down_revision: Union[str, None] = "985f4e37b466"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financing_agent",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financing_agent_created_at"),
        "financing_agent",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_agent_created_by"),
        "financing_agent",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_agent_deleted_by"),
        "financing_agent",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_agent_deleted_status"),
        "financing_agent",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_agent_last_updated_at"),
        "financing_agent",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_agent_last_updated_by"),
        "financing_agent",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_agent_name"), "financing_agent", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_financing_agent_sha_code"),
        "financing_agent",
        ["sha_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_agent_uuid"), "financing_agent", ["uuid"], unique=True
    )
    op.create_table(
        "financing_scheme",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financing_scheme_created_at"),
        "financing_scheme",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_scheme_created_by"),
        "financing_scheme",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_scheme_deleted_by"),
        "financing_scheme",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_scheme_deleted_status"),
        "financing_scheme",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_scheme_last_updated_at"),
        "financing_scheme",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_scheme_last_updated_by"),
        "financing_scheme",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_scheme_name"), "financing_scheme", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_financing_scheme_sha_code"),
        "financing_scheme",
        ["sha_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financing_scheme_uuid"), "financing_scheme", ["uuid"], unique=True
    )
    op.create_table(
        "health_care_provider",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_health_care_provider_created_at"),
        "health_care_provider",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_created_by"),
        "health_care_provider",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_deleted_by"),
        "health_care_provider",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_deleted_status"),
        "health_care_provider",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_last_updated_at"),
        "health_care_provider",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_last_updated_by"),
        "health_care_provider",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_name"),
        "health_care_provider",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_sha_code"),
        "health_care_provider",
        ["sha_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_health_care_provider_uuid"),
        "health_care_provider",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "sub_financing_agent",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("financing_agent_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["financing_agent_uuid"],
            ["financing_agent.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sub_financing_agent_created_at"),
        "sub_financing_agent",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_created_by"),
        "sub_financing_agent",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_deleted_by"),
        "sub_financing_agent",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_deleted_status"),
        "sub_financing_agent",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_financing_agent_uuid"),
        "sub_financing_agent",
        ["financing_agent_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_last_updated_at"),
        "sub_financing_agent",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_last_updated_by"),
        "sub_financing_agent",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_name"),
        "sub_financing_agent",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_sha_code"),
        "sub_financing_agent",
        ["sha_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_agent_uuid"),
        "sub_financing_agent",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "sub_financing_scheme",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "financing_scheme_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["financing_scheme_uuid"],
            ["financing_scheme.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_created_at"),
        "sub_financing_scheme",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_created_by"),
        "sub_financing_scheme",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_deleted_by"),
        "sub_financing_scheme",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_deleted_status"),
        "sub_financing_scheme",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_last_updated_at"),
        "sub_financing_scheme",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_last_updated_by"),
        "sub_financing_scheme",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_name"),
        "sub_financing_scheme",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_sha_code"),
        "sub_financing_scheme",
        ["sha_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_financing_scheme_uuid"),
        "sub_financing_scheme",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "sub_health_care_provider",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "health_care_provider_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sha_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["health_care_provider_uuid"],
            ["health_care_provider.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_created_at"),
        "sub_health_care_provider",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_created_by"),
        "sub_health_care_provider",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_deleted_by"),
        "sub_health_care_provider",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_deleted_status"),
        "sub_health_care_provider",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_last_updated_at"),
        "sub_health_care_provider",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_last_updated_by"),
        "sub_health_care_provider",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_name"),
        "sub_health_care_provider",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_sha_code"),
        "sub_health_care_provider",
        ["sha_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sub_health_care_provider_uuid"),
        "sub_health_care_provider",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "organization_financing_agent",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("financing_agent_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["financing_agent_uuid"],
            ["financing_agent.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_uuid"],
            ["organization.uuid"],
        ),
        sa.PrimaryKeyConstraint("id", "organization_uuid", "financing_agent_uuid"),
    )
    op.create_index(
        op.f("ix_organization_financing_agent_created_at"),
        "organization_financing_agent",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_agent_created_by"),
        "organization_financing_agent",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_agent_deleted_by"),
        "organization_financing_agent",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_agent_deleted_status"),
        "organization_financing_agent",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_agent_last_updated_at"),
        "organization_financing_agent",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_agent_last_updated_by"),
        "organization_financing_agent",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_agent_uuid"),
        "organization_financing_agent",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "organization_financing_scheme",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "financing_scheme_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["financing_scheme_uuid"],
            ["financing_scheme.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_uuid"],
            ["organization.uuid"],
        ),
        sa.PrimaryKeyConstraint("id", "organization_uuid", "financing_scheme_uuid"),
    )
    op.create_index(
        op.f("ix_organization_financing_scheme_created_at"),
        "organization_financing_scheme",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_scheme_created_by"),
        "organization_financing_scheme",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_scheme_deleted_by"),
        "organization_financing_scheme",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_scheme_deleted_status"),
        "organization_financing_scheme",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_scheme_last_updated_at"),
        "organization_financing_scheme",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_scheme_last_updated_by"),
        "organization_financing_scheme",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_financing_scheme_uuid"),
        "organization_financing_scheme",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "organization_health_care_provider",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "health_care_provider_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["health_care_provider_uuid"],
            ["health_care_provider.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_uuid"],
            ["organization.uuid"],
        ),
        sa.PrimaryKeyConstraint("id", "organization_uuid", "health_care_provider_uuid"),
    )
    op.create_index(
        op.f("ix_organization_health_care_provider_created_at"),
        "organization_health_care_provider",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_health_care_provider_created_by"),
        "organization_health_care_provider",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_health_care_provider_deleted_by"),
        "organization_health_care_provider",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_health_care_provider_deleted_status"),
        "organization_health_care_provider",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_health_care_provider_last_updated_at"),
        "organization_health_care_provider",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_health_care_provider_last_updated_by"),
        "organization_health_care_provider",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_health_care_provider_uuid"),
        "organization_health_care_provider",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "organization_sub_financing_agent",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "sub_financing_agent_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_uuid"],
            ["organization.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_financing_agent_uuid"],
            ["sub_financing_agent.uuid"],
        ),
        sa.PrimaryKeyConstraint("id", "organization_uuid", "sub_financing_agent_uuid"),
    )
    op.create_index(
        op.f("ix_organization_sub_financing_agent_created_at"),
        "organization_sub_financing_agent",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_agent_created_by"),
        "organization_sub_financing_agent",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_agent_deleted_by"),
        "organization_sub_financing_agent",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_agent_deleted_status"),
        "organization_sub_financing_agent",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_agent_last_updated_at"),
        "organization_sub_financing_agent",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_agent_last_updated_by"),
        "organization_sub_financing_agent",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_agent_uuid"),
        "organization_sub_financing_agent",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "organization_sub_financing_scheme",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "sub_financing_scheme_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_uuid"],
            ["organization.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_financing_scheme_uuid"],
            ["sub_financing_scheme.uuid"],
        ),
        sa.PrimaryKeyConstraint("id", "organization_uuid", "sub_financing_scheme_uuid"),
    )
    op.create_index(
        op.f("ix_organization_sub_financing_scheme_created_at"),
        "organization_sub_financing_scheme",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_scheme_created_by"),
        "organization_sub_financing_scheme",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_scheme_deleted_by"),
        "organization_sub_financing_scheme",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_scheme_deleted_status"),
        "organization_sub_financing_scheme",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_scheme_last_updated_at"),
        "organization_sub_financing_scheme",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_scheme_last_updated_by"),
        "organization_sub_financing_scheme",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_financing_scheme_uuid"),
        "organization_sub_financing_scheme",
        ["uuid"],
        unique=True,
    )
    op.create_table(
        "organization_sub_health_care_provider",
        sa.Column("uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted_status", sa.Boolean(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("deleted_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("organization_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column(
            "sub_healthcare_provider_uuid", sqlmodel.sql.sqltypes.GUID(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["organization_uuid"],
            ["organization.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_healthcare_provider_uuid"],
            ["sub_health_care_provider.uuid"],
        ),
        sa.PrimaryKeyConstraint(
            "id", "organization_uuid", "sub_healthcare_provider_uuid"
        ),
    )
    op.create_index(
        op.f("ix_organization_sub_health_care_provider_created_at"),
        "organization_sub_health_care_provider",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_health_care_provider_created_by"),
        "organization_sub_health_care_provider",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_health_care_provider_deleted_by"),
        "organization_sub_health_care_provider",
        ["deleted_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_health_care_provider_deleted_status"),
        "organization_sub_health_care_provider",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_health_care_provider_last_updated_at"),
        "organization_sub_health_care_provider",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_health_care_provider_last_updated_by"),
        "organization_sub_health_care_provider",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_sub_health_care_provider_uuid"),
        "organization_sub_health_care_provider",
        ["uuid"],
        unique=True,
    )
    op.drop_index("ix_user_domain_created_at", table_name="user_domain")
    op.drop_index("ix_user_domain_created_by", table_name="user_domain")
    op.drop_index("ix_user_domain_deleted_by", table_name="user_domain")
    op.drop_index("ix_user_domain_deleted_status", table_name="user_domain")
    op.drop_index("ix_user_domain_domain_id", table_name="user_domain")
    op.drop_index("ix_user_domain_last_updated_at", table_name="user_domain")
    op.drop_index("ix_user_domain_last_updated_by", table_name="user_domain")
    op.drop_index("ix_user_domain_user_id", table_name="user_domain")
    op.drop_index("ix_user_domain_uuid", table_name="user_domain")
    op.drop_table("user_domain")
    op.drop_index("ix_user_activity_activity_uuid", table_name="user_activity")
    op.drop_index("ix_user_activity_created_at", table_name="user_activity")
    op.drop_index("ix_user_activity_created_by", table_name="user_activity")
    op.drop_index("ix_user_activity_deleted_by", table_name="user_activity")
    op.drop_index("ix_user_activity_deleted_status", table_name="user_activity")
    op.drop_index("ix_user_activity_last_updated_at", table_name="user_activity")
    op.drop_index("ix_user_activity_last_updated_by", table_name="user_activity")
    op.drop_index("ix_user_activity_user_uuid", table_name="user_activity")
    op.drop_index("ix_user_activity_uuid", table_name="user_activity")
    op.drop_table("user_activity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activity",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("deleted_status", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "last_updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("last_updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("activity_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_uuid"],
            ["activity.uuid"],
            name="user_activity_activity_uuid_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name="user_activity_user_uuid_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_activity_pkey"),
    )
    op.create_index("ix_user_activity_uuid", "user_activity", ["uuid"], unique=True)
    op.create_index(
        "ix_user_activity_user_uuid", "user_activity", ["user_uuid"], unique=False
    )
    op.create_index(
        "ix_user_activity_last_updated_by",
        "user_activity",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        "ix_user_activity_last_updated_at",
        "user_activity",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_user_activity_deleted_status",
        "user_activity",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        "ix_user_activity_deleted_by", "user_activity", ["deleted_by"], unique=False
    )
    op.create_index(
        "ix_user_activity_created_by", "user_activity", ["created_by"], unique=False
    )
    op.create_index(
        "ix_user_activity_created_at", "user_activity", ["created_at"], unique=False
    )
    op.create_index(
        "ix_user_activity_activity_uuid",
        "user_activity",
        ["activity_uuid"],
        unique=False,
    )
    op.create_table(
        "user_domain",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("deleted_status", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "last_updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("last_updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("domain_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "subdomain_ids",
            postgresql.ARRAY(sa.UUID()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain_intervention.uuid"],
            name="user_domain_domain_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.uuid"], name="user_domain_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_domain_pkey"),
    )
    op.create_index("ix_user_domain_uuid", "user_domain", ["uuid"], unique=True)
    op.create_index("ix_user_domain_user_id", "user_domain", ["user_id"], unique=False)
    op.create_index(
        "ix_user_domain_last_updated_by",
        "user_domain",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        "ix_user_domain_last_updated_at",
        "user_domain",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_user_domain_domain_id", "user_domain", ["domain_id"], unique=False
    )
    op.create_index(
        "ix_user_domain_deleted_status", "user_domain", ["deleted_status"], unique=False
    )
    op.create_index(
        "ix_user_domain_deleted_by", "user_domain", ["deleted_by"], unique=False
    )
    op.create_index(
        "ix_user_domain_created_by", "user_domain", ["created_by"], unique=False
    )
    op.create_index(
        "ix_user_domain_created_at", "user_domain", ["created_at"], unique=False
    )
    op.drop_index(
        op.f("ix_organization_sub_health_care_provider_uuid"),
        table_name="organization_sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_sub_health_care_provider_last_updated_by"),
        table_name="organization_sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_sub_health_care_provider_last_updated_at"),
        table_name="organization_sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_sub_health_care_provider_deleted_status"),
        table_name="organization_sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_sub_health_care_provider_deleted_by"),
        table_name="organization_sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_sub_health_care_provider_created_by"),
        table_name="organization_sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_sub_health_care_provider_created_at"),
        table_name="organization_sub_health_care_provider",
    )
    op.drop_table("organization_sub_health_care_provider")
    op.drop_index(
        op.f("ix_organization_sub_financing_scheme_uuid"),
        table_name="organization_sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_scheme_last_updated_by"),
        table_name="organization_sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_scheme_last_updated_at"),
        table_name="organization_sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_scheme_deleted_status"),
        table_name="organization_sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_scheme_deleted_by"),
        table_name="organization_sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_scheme_created_by"),
        table_name="organization_sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_scheme_created_at"),
        table_name="organization_sub_financing_scheme",
    )
    op.drop_table("organization_sub_financing_scheme")
    op.drop_index(
        op.f("ix_organization_sub_financing_agent_uuid"),
        table_name="organization_sub_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_agent_last_updated_by"),
        table_name="organization_sub_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_agent_last_updated_at"),
        table_name="organization_sub_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_agent_deleted_status"),
        table_name="organization_sub_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_agent_deleted_by"),
        table_name="organization_sub_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_agent_created_by"),
        table_name="organization_sub_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_sub_financing_agent_created_at"),
        table_name="organization_sub_financing_agent",
    )
    op.drop_table("organization_sub_financing_agent")
    op.drop_index(
        op.f("ix_organization_health_care_provider_uuid"),
        table_name="organization_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_health_care_provider_last_updated_by"),
        table_name="organization_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_health_care_provider_last_updated_at"),
        table_name="organization_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_health_care_provider_deleted_status"),
        table_name="organization_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_health_care_provider_deleted_by"),
        table_name="organization_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_health_care_provider_created_by"),
        table_name="organization_health_care_provider",
    )
    op.drop_index(
        op.f("ix_organization_health_care_provider_created_at"),
        table_name="organization_health_care_provider",
    )
    op.drop_table("organization_health_care_provider")
    op.drop_index(
        op.f("ix_organization_financing_scheme_uuid"),
        table_name="organization_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_financing_scheme_last_updated_by"),
        table_name="organization_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_financing_scheme_last_updated_at"),
        table_name="organization_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_financing_scheme_deleted_status"),
        table_name="organization_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_financing_scheme_deleted_by"),
        table_name="organization_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_financing_scheme_created_by"),
        table_name="organization_financing_scheme",
    )
    op.drop_index(
        op.f("ix_organization_financing_scheme_created_at"),
        table_name="organization_financing_scheme",
    )
    op.drop_table("organization_financing_scheme")
    op.drop_index(
        op.f("ix_organization_financing_agent_uuid"),
        table_name="organization_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_financing_agent_last_updated_by"),
        table_name="organization_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_financing_agent_last_updated_at"),
        table_name="organization_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_financing_agent_deleted_status"),
        table_name="organization_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_financing_agent_deleted_by"),
        table_name="organization_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_financing_agent_created_by"),
        table_name="organization_financing_agent",
    )
    op.drop_index(
        op.f("ix_organization_financing_agent_created_at"),
        table_name="organization_financing_agent",
    )
    op.drop_table("organization_financing_agent")
    op.drop_index(
        op.f("ix_sub_health_care_provider_uuid"), table_name="sub_health_care_provider"
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_sha_code"),
        table_name="sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_name"), table_name="sub_health_care_provider"
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_last_updated_by"),
        table_name="sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_last_updated_at"),
        table_name="sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_deleted_status"),
        table_name="sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_deleted_by"),
        table_name="sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_created_by"),
        table_name="sub_health_care_provider",
    )
    op.drop_index(
        op.f("ix_sub_health_care_provider_created_at"),
        table_name="sub_health_care_provider",
    )
    op.drop_table("sub_health_care_provider")
    op.drop_index(
        op.f("ix_sub_financing_scheme_uuid"), table_name="sub_financing_scheme"
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_sha_code"), table_name="sub_financing_scheme"
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_name"), table_name="sub_financing_scheme"
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_last_updated_by"),
        table_name="sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_last_updated_at"),
        table_name="sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_deleted_status"),
        table_name="sub_financing_scheme",
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_deleted_by"), table_name="sub_financing_scheme"
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_created_by"), table_name="sub_financing_scheme"
    )
    op.drop_index(
        op.f("ix_sub_financing_scheme_created_at"), table_name="sub_financing_scheme"
    )
    op.drop_table("sub_financing_scheme")
    op.drop_index(op.f("ix_sub_financing_agent_uuid"), table_name="sub_financing_agent")
    op.drop_index(
        op.f("ix_sub_financing_agent_sha_code"), table_name="sub_financing_agent"
    )
    op.drop_index(op.f("ix_sub_financing_agent_name"), table_name="sub_financing_agent")
    op.drop_index(
        op.f("ix_sub_financing_agent_last_updated_by"), table_name="sub_financing_agent"
    )
    op.drop_index(
        op.f("ix_sub_financing_agent_last_updated_at"), table_name="sub_financing_agent"
    )
    op.drop_index(
        op.f("ix_sub_financing_agent_financing_agent_uuid"),
        table_name="sub_financing_agent",
    )
    op.drop_index(
        op.f("ix_sub_financing_agent_deleted_status"), table_name="sub_financing_agent"
    )
    op.drop_index(
        op.f("ix_sub_financing_agent_deleted_by"), table_name="sub_financing_agent"
    )
    op.drop_index(
        op.f("ix_sub_financing_agent_created_by"), table_name="sub_financing_agent"
    )
    op.drop_index(
        op.f("ix_sub_financing_agent_created_at"), table_name="sub_financing_agent"
    )
    op.drop_table("sub_financing_agent")
    op.drop_index(
        op.f("ix_health_care_provider_uuid"), table_name="health_care_provider"
    )
    op.drop_index(
        op.f("ix_health_care_provider_sha_code"), table_name="health_care_provider"
    )
    op.drop_index(
        op.f("ix_health_care_provider_name"), table_name="health_care_provider"
    )
    op.drop_index(
        op.f("ix_health_care_provider_last_updated_by"),
        table_name="health_care_provider",
    )
    op.drop_index(
        op.f("ix_health_care_provider_last_updated_at"),
        table_name="health_care_provider",
    )
    op.drop_index(
        op.f("ix_health_care_provider_deleted_status"),
        table_name="health_care_provider",
    )
    op.drop_index(
        op.f("ix_health_care_provider_deleted_by"), table_name="health_care_provider"
    )
    op.drop_index(
        op.f("ix_health_care_provider_created_by"), table_name="health_care_provider"
    )
    op.drop_index(
        op.f("ix_health_care_provider_created_at"), table_name="health_care_provider"
    )
    op.drop_table("health_care_provider")
    op.drop_index(op.f("ix_financing_scheme_uuid"), table_name="financing_scheme")
    op.drop_index(op.f("ix_financing_scheme_sha_code"), table_name="financing_scheme")
    op.drop_index(op.f("ix_financing_scheme_name"), table_name="financing_scheme")
    op.drop_index(
        op.f("ix_financing_scheme_last_updated_by"), table_name="financing_scheme"
    )
    op.drop_index(
        op.f("ix_financing_scheme_last_updated_at"), table_name="financing_scheme"
    )
    op.drop_index(
        op.f("ix_financing_scheme_deleted_status"), table_name="financing_scheme"
    )
    op.drop_index(op.f("ix_financing_scheme_deleted_by"), table_name="financing_scheme")
    op.drop_index(op.f("ix_financing_scheme_created_by"), table_name="financing_scheme")
    op.drop_index(op.f("ix_financing_scheme_created_at"), table_name="financing_scheme")
    op.drop_table("financing_scheme")
    op.drop_index(op.f("ix_financing_agent_uuid"), table_name="financing_agent")
    op.drop_index(op.f("ix_financing_agent_sha_code"), table_name="financing_agent")
    op.drop_index(op.f("ix_financing_agent_name"), table_name="financing_agent")
    op.drop_index(
        op.f("ix_financing_agent_last_updated_by"), table_name="financing_agent"
    )
    op.drop_index(
        op.f("ix_financing_agent_last_updated_at"), table_name="financing_agent"
    )
    op.drop_index(
        op.f("ix_financing_agent_deleted_status"), table_name="financing_agent"
    )
    op.drop_index(op.f("ix_financing_agent_deleted_by"), table_name="financing_agent")
    op.drop_index(op.f("ix_financing_agent_created_by"), table_name="financing_agent")
    op.drop_index(op.f("ix_financing_agent_created_at"), table_name="financing_agent")
    op.drop_table("financing_agent")
    # ### end Alembic commands ###
