"""Update remove types from party model

Revision ID: 9ff86bbf7ecc
Revises: 
Create Date: 2024-05-12 16:47:57.966854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ff86bbf7ecc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('type', postgresql.ENUM('ORGANIZATION', 'MINISTRY', name='partytype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
