"""Add modified status,  Change modified entities enum

Revision ID: a4edd5f53b83
Revises: d7989dfc2302
Create Date: 2024-06-23 15:09:12.372401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'a4edd5f53b83'
down_revision: Union[str, None] = 'd7989dfc2302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'mouapplicationstatus', ['PENDING', 'UNDER_REVIEW', 'READY_FOR_APPROVAL', 'UNDER_APPROVAL', 'APPROVED', 'REJECTED', 'REQUEST_MODIFICATION', 'MODIFIED'],
                        [TableReference(table_schema='public', table_name='mou_application', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'mouapplicationstatus', ['PENDING', 'UNDER_REVIEW', 'READY_FOR_APPROVAL', 'UNDER_APPROVAL', 'APPROVED', 'REJECTED', 'REQUEST_MODIFICATION'],
                        [TableReference(table_schema='public', table_name='mou_application', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
