"""Make mou documents a list

Revision ID: a6f00b38978f
Revises: b8493bfa0d44
Create Date: 2024-05-08 01:39:45.768360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f00b38978f'
down_revision: Union[str, None] = 'b8493bfa0d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mou_document_id_fkey', 'mou', type_='foreignkey')
    op.drop_column('mou', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('mou_document_id_fkey', 'mou', 'document', ['document_id'], ['uuid'])
    # ### end Alembic commands ###
