"""changes

Revision ID: b23a884e9ace
Revises: 4333a9277e04
Create Date: 2024-11-24 18:35:57.175344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b23a884e9ace"
down_revision: Union[str, None] = "4333a9277e04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_domain_created_at", table_name="user_domain")
    op.drop_index("ix_user_domain_created_by", table_name="user_domain")
    op.drop_index("ix_user_domain_deleted_by", table_name="user_domain")
    op.drop_index("ix_user_domain_deleted_status", table_name="user_domain")
    op.drop_index("ix_user_domain_domain_id", table_name="user_domain")
    op.drop_index("ix_user_domain_last_updated_at", table_name="user_domain")
    op.drop_index("ix_user_domain_last_updated_by", table_name="user_domain")
    op.drop_index("ix_user_domain_user_id", table_name="user_domain")
    op.drop_index("ix_user_domain_uuid", table_name="user_domain")
    op.drop_table("user_domain")
    op.drop_index("ix_user_activity_activity_uuid", table_name="user_activity")
    op.drop_index("ix_user_activity_created_at", table_name="user_activity")
    op.drop_index("ix_user_activity_created_by", table_name="user_activity")
    op.drop_index("ix_user_activity_deleted_by", table_name="user_activity")
    op.drop_index("ix_user_activity_deleted_status", table_name="user_activity")
    op.drop_index("ix_user_activity_last_updated_at", table_name="user_activity")
    op.drop_index("ix_user_activity_last_updated_by", table_name="user_activity")
    op.drop_index("ix_user_activity_user_uuid", table_name="user_activity")
    op.drop_index("ix_user_activity_uuid", table_name="user_activity")
    op.drop_table("user_activity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activity",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("deleted_status", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "last_updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("last_updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("activity_uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_uuid"],
            ["activity.uuid"],
            name="user_activity_activity_uuid_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"], ["user.uuid"], name="user_activity_user_uuid_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_activity_pkey"),
    )
    op.create_index("ix_user_activity_uuid", "user_activity", ["uuid"], unique=True)
    op.create_index(
        "ix_user_activity_user_uuid", "user_activity", ["user_uuid"], unique=False
    )
    op.create_index(
        "ix_user_activity_last_updated_by",
        "user_activity",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        "ix_user_activity_last_updated_at",
        "user_activity",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_user_activity_deleted_status",
        "user_activity",
        ["deleted_status"],
        unique=False,
    )
    op.create_index(
        "ix_user_activity_deleted_by", "user_activity", ["deleted_by"], unique=False
    )
    op.create_index(
        "ix_user_activity_created_by", "user_activity", ["created_by"], unique=False
    )
    op.create_index(
        "ix_user_activity_created_at", "user_activity", ["created_at"], unique=False
    )
    op.create_index(
        "ix_user_activity_activity_uuid",
        "user_activity",
        ["activity_uuid"],
        unique=False,
    )
    op.create_table(
        "user_domain",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("deleted_status", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "last_updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("last_updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("deleted_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("domain_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "subdomain_ids",
            postgresql.ARRAY(sa.UUID()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain_intervention.uuid"],
            name="user_domain_domain_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.uuid"], name="user_domain_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_domain_pkey"),
    )
    op.create_index("ix_user_domain_uuid", "user_domain", ["uuid"], unique=True)
    op.create_index("ix_user_domain_user_id", "user_domain", ["user_id"], unique=False)
    op.create_index(
        "ix_user_domain_last_updated_by",
        "user_domain",
        ["last_updated_by"],
        unique=False,
    )
    op.create_index(
        "ix_user_domain_last_updated_at",
        "user_domain",
        ["last_updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_user_domain_domain_id", "user_domain", ["domain_id"], unique=False
    )
    op.create_index(
        "ix_user_domain_deleted_status", "user_domain", ["deleted_status"], unique=False
    )
    op.create_index(
        "ix_user_domain_deleted_by", "user_domain", ["deleted_by"], unique=False
    )
    op.create_index(
        "ix_user_domain_created_by", "user_domain", ["created_by"], unique=False
    )
    op.create_index(
        "ix_user_domain_created_at", "user_domain", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
