"""Fix funding source

Revision ID: bdc472dbf3d0
Revises: 
Create Date: 2024-04-28 18:05:01.581626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bdc472dbf3d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operational_zone_created_at', table_name='operational_zone')
    op.drop_index('ix_operational_zone_uuid', table_name='operational_zone')
    op.drop_table('operational_zone')
    op.drop_index('ix_project_created_at', table_name='project')
    op.drop_index('ix_project_uuid', table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('project_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain_intervention_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('budget_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('planned_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('funding_unit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('funding_source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['budget_type_id'], ['budget_type.uuid'], name='project_budget_type_id_fkey'),
    sa.ForeignKeyConstraint(['domain_intervention_id'], ['domain_intervention.uuid'], name='project_domain_intervention_id_fkey'),
    sa.ForeignKeyConstraint(['funding_source_id'], ['funding_source.uuid'], name='project_funding_source_id_fkey'),
    sa.ForeignKeyConstraint(['funding_unit_id'], ['funding_unit.uuid'], name='project_funding_unit_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.uuid'], name='project_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_project_uuid', 'project', ['uuid'], unique=True)
    op.create_index('ix_project_created_at', 'project', ['created_at'], unique=False)
    op.create_table('operational_zone',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provinces', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('districts', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.uuid'], name='operational_zone_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='operational_zone_pkey')
    )
    op.create_index('ix_operational_zone_uuid', 'operational_zone', ['uuid'], unique=True)
    op.create_index('ix_operational_zone_created_at', 'operational_zone', ['created_at'], unique=False)
    # ### end Alembic commands ###
