"""Project: optional duration field

Revision ID: c2148c0c4e9f
Revises: 4bae06203ae7
Create Date: 2024-07-23 22:01:07.347116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2148c0c4e9f'
down_revision: Union[str, None] = '4bae06203ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'duration')
    # ### end Alembic commands ###
