"""Correct spelling over all goal

Revision ID: c39777987217
Revises: 5319d98ee2b2
Create Date: 2024-06-26 22:31:04.013008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c39777987217'
down_revision: Union[str, None] = '5319d98ee2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('overall_goal', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('project', 'overall_gaol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('overall_gaol', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('project', 'overall_goal')
    # ### end Alembic commands ###
