"""changes

Revision ID: c49e2cb7b8f6
Revises: 434469f655de
Create Date: 2024-05-02 22:47:44.845184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c49e2cb7b8f6'
down_revision: Union[str, None] = '434469f655de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_comment', sa.Column('mou_approval_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column('mou_comment', sa.Column('mou_review_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'mou_comment', 'mou_review', ['mou_review_id'], ['uuid'])
    op.create_foreign_key(None, 'mou_comment', 'mou_approval', ['mou_approval_id'], ['uuid'])
    op.add_column('party', sa.Column('mou_detail_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'party', 'mou_detail', ['mou_detail_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'party', type_='foreignkey')
    op.drop_column('party', 'mou_detail_id')
    op.drop_constraint(None, 'mou_comment', type_='foreignkey')
    op.drop_constraint(None, 'mou_comment', type_='foreignkey')
    op.drop_column('mou_comment', 'mou_review_id')
    op.drop_column('mou_comment', 'mou_approval_id')
    # ### end Alembic commands ###
