"""changes project

Revision ID: c6fd67e9ef06
Revises: c49e2cb7b8f6
Create Date: 2024-05-03 01:25:16.155968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6fd67e9ef06'
down_revision: Union[str, None] = 'c49e2cb7b8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('mou_detail_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'document', 'mou_detail', ['mou_detail_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'mou_detail_id')
    # ### end Alembic commands ###
