"""Create mou approvals or reviews model

Revision ID: cddcef70e907
Revises: a4ab4270f268
Create Date: 2024-05-19 00:06:24.070860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cddcef70e907'
down_revision: Union[str, None] = 'a4ab4270f268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_comment', sa.Column('mou_approval_or_review_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'mou_comment', 'mou_approval_or_review', ['mou_approval_or_review_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mou_comment', type_='foreignkey')
    op.drop_column('mou_comment', 'mou_approval_or_review_id')
    # ### end Alembic commands ###
