"""User model: add organization foreign keys

Revision ID: d6aba7d4b57f
Revises: 17db56adc781
Create Date: 2024-07-17 12:57:59.067045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6aba7d4b57f'
down_revision: Union[str, None] = '17db56adc781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization_uuid', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization', ['organization_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'organization_uuid')
    # ### end Alembic commands ###
