"""Move duration to party

Revision ID: d7989dfc2302
Revises: 647667b3e430
Create Date: 2024-06-21 12:59:18.214658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd7989dfc2302'
down_revision: Union[str, None] = '647667b3e430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mou_detail', 'duration')
    op.add_column('party', sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'duration')
    op.add_column('mou_detail', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
