"""User: assign domain and subdomains

Revision ID: d7a9a8813185
Revises: 
Create Date: 2024-07-28 23:46:15.708549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a9a8813185'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sub_domain_created_at', table_name='user_sub_domain')
    op.drop_index('ix_user_sub_domain_uuid', table_name='user_sub_domain')
    op.drop_table('user_sub_domain')
    op.drop_constraint('user_assigned_domain_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'assigned_domain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('assigned_domain_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_assigned_domain_id_fkey', 'user', 'domain_intervention', ['assigned_domain_id'], ['uuid'])
    op.create_table('user_sub_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sub_domain_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sub_domain_uuid'], ['sub_domain.uuid'], name='user_sub_domain_sub_domain_uuid_fkey'),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name='user_sub_domain_user_uuid_fkey'),
    sa.PrimaryKeyConstraint('id', 'user_uuid', 'sub_domain_uuid', name='user_sub_domain_pkey')
    )
    op.create_index('ix_user_sub_domain_uuid', 'user_sub_domain', ['uuid'], unique=True)
    op.create_index('ix_user_sub_domain_created_at', 'user_sub_domain', ['created_at'], unique=False)
    # ### end Alembic commands ###
