"""changes

Revision ID: dfd74828e2cd
Revises: 082fc163a744
Create Date: 2024-11-28 02:21:47.969204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dfd74828e2cd"
down_revision: Union[str, None] = "082fc163a744"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password_reset_token_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_reset_token_expires")
    # ### end Alembic commands ###
