"""Application: template comment

Revision ID: e3c5a2ce30f8
Revises: c2148c0c4e9f
Create Date: 2024-07-24 10:10:09.470588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3c5a2ce30f8'
down_revision: Union[str, None] = 'c2148c0c4e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_application', sa.Column('partner_template_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mou_application', 'partner_template_comment')
    # ### end Alembic commands ###
