"""Add missing values to documenttype enum upper case

Revision ID: e4e95a7725fc
Revises: 32e9729936de
Create Date: 2024-05-03 01:51:50.642987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e95a7725fc'
down_revision: Union[str, None] = '32e9729936de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'MEMO_DESCRIBING_THE_SOURCE_OF_FUNDS'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'MEMO_DESCRIBING_THE_LONG_TERM_OBJECTIVES'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'CAPACITY_BUILDING_TRANSFER_PLAN'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'STRATEGIC_PLAN'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'ADDITIONAL_DOCUMENT'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
