"""Add last_decision_date field to MouApplication

Revision ID: ecae408ff041
Revises: 4bfdea6c72ea
Create Date: 2024-06-10 10:56:25.018994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecae408ff041'
down_revision: Union[str, None] = '4bfdea6c72ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mou_application', sa.Column('last_decision_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mou_application', 'last_decision_date')
    # ### end Alembic commands ###
