"""Update start and end dates

Revision ID: eec46e9d92d1
Revises: 671839e78d93
Create Date: 2024-05-09 22:47:08.950744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec46e9d92d1'
down_revision: Union[str, None] = '671839e78d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the columns as nullable
    op.add_column('activity', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('activity', sa.Column('end_date', sa.Date(), nullable=True))

    # Populate the columns with appropriate values
    op.execute("UPDATE activity SET start_date = project.start_date FROM project WHERE activity.project_id = project.uuid")
    op.execute("UPDATE activity SET end_date = project.end_date FROM project WHERE activity.project_id = project.uuid")

    # Alter the columns to be NOT NULL
    op.alter_column('activity', 'start_date', nullable=False)
    op.alter_column('activity', 'end_date', nullable=False)

    # Drop the columns from the project table
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the columns back to the project table
    op.add_column('project', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('project', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))

    # Populate the columns in the project table with appropriate values
    op.execute("UPDATE project SET start_date = activity.start_date FROM activity WHERE project.uuid = activity.project_id")
    op.execute("UPDATE project SET end_date = activity.end_date FROM activity WHERE project.uuid = activity.project_id")

    # Drop the columns from the activity table
    op.drop_column('activity', 'end_date')
    op.drop_column('activity', 'start_date')
    # ### end Alembic commands ###
