"""User: assign domain and subdomains

Revision ID: ffbf654c6bc2
Revises: d7a9a8813185
Create Date: 2024-07-28 23:53:21.801725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffbf654c6bc2'
down_revision: Union[str, None] = 'd7a9a8813185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_domain_created_at', table_name='user_domain')
    op.drop_index('ix_user_domain_uuid', table_name='user_domain')
    op.drop_table('user_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_domain',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deleted_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_updated_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subdomain_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain_intervention.uuid'], name='user_domain_domain_id_fkey'),
    sa.ForeignKeyConstraint(['subdomain_id'], ['sub_domain.uuid'], name='user_domain_subdomain_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], name='user_domain_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_domain_pkey')
    )
    op.create_index('ix_user_domain_uuid', 'user_domain', ['uuid'], unique=True)
    op.create_index('ix_user_domain_created_at', 'user_domain', ['created_at'], unique=False)
    # ### end Alembic commands ###
